### ISSUE TITLE
market failed to parse koishi-plugin-petpet

### ISSUE THREAD

**Issue by CrazyBoyM** [univeous/koishi-plugin-petpet#1]
market failed to parse koishi-plugin-petpet
最新版本无法使用。

**Comment by univeous** [comment]
我这里没办法复现。其他插件都没问题吗？

**Comment by CrazyBoyM** [comment]
其他插件没问题，正常的。


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 00:46 AM
To: ***@***.***&gt;;
Cc: &quot;Ke ***@***.******@***.***&gt;;
Subject: Re: [univeous/koishi-plugin-petpet] market failed to parse koishi-plugin-petpet (Issue #1)




 
我这里没办法复现。其他插件都没问题吗？
 
&mdash;

**Comment by univeous** [comment]
可以贴package.json和koishi配置看一下，你也可以删掉yarn.lock和node_modules，重新跑一下yarn看看。

**Comment by LexaTang** [comment]
> 

NPM包里没有lib文件夹和代码。1.0.5版本

**Comment by univeous** [comment]
> > 
> 
> NPM包里没有lib文件夹和代码。1.0.5版本

……非常非常抱歉。1.0.6版本已经修复了。

**Comment by LexaTang** [comment]
> > > 
> > 
> > 
> > NPM包里没有lib文件夹和代码。1.0.5版本
> 
> ……非常非常抱歉。1.0.6版本已经修复了。

没事的哈哈！非常感谢
